<?php

/**
 *  Change layout of page to have no wrappers when on calling meteo service
 *
 */
function instagram_theme_suggestions_page_alter(array &$suggestions, array $variables) {

	if(
	    strpos(\Drupal::service('path.current')->getPath(), 'instagram/generate') !== false ||
        strpos(\Drupal::service('path.current')->getPath(), 'instagram/render_images') !== false
    ){
		$suggestions[] = 'page__ajax';
	}
	
}



/**
 *  Change layout of html to have no wrappers when on calling meteo service
 *
 */
function instagram_theme_suggestions_html_alter(array &$suggestions, array $variables) {
        
	if(
        strpos(\Drupal::service('path.current')->getPath(), 'instagram/generate') !== false ||
        strpos(\Drupal::service('path.current')->getPath(), 'instagram/render_images') !== false
    ){
		$suggestions[] = 'html__ajax';
	}
        
}
